# Generated by Django 4.2.11 on 2024-05-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BloodGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BLOOD_GROUPNAME", models.CharField(max_length=1000)),
                ("BLOOD_GROUPDESC", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="DonateBlood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DONOR_NAME", models.CharField(max_length=1000)),
                ("DONOR_BLOODGROUPNAME", models.CharField(max_length=1000)),
                ("DONOR_DATE", models.CharField(max_length=1000)),
                ("DONOR_QTY", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="PersonDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PER_NAME", models.CharField(max_length=1000)),
                ("PER_PHONENO", models.CharField(max_length=1000)),
                ("PER_EMAIL", models.CharField(max_length=1000)),
                ("PER_ADDRESS", models.CharField(max_length=1000)),
                ("PER_DOB", models.CharField(max_length=1000)),
                ("PER_BLOODGROUPNAME", models.CharField(max_length=1000)),
            ],
        ),
    ]
